import type { Metadata } from "next";

import "./globals.css";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Header />
        <div className="flex h-screen overflow-hidden">
          <div className="hidden md:block">
            <Sidebar />
          </div>
          <div className="flex-1 bg-[#fcfcfc] md:p-6 p-3 md:overflow-auto">
            <Providers> {children} </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
